# Generated by Django 3.0 on 2021-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwrate', '0005_auto_20210719_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
