# Generated by Django 3.0 on 2021-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwrate', '0007_auto_20210720_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['posted_at']},
        ),
        migrations.AlterField(
            model_name='review',
            name='content_rating',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='design_rating',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability_rating',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
